import { NoteState, CategoryNames } from "./noteReducerTypes";

export const initialState: NoteState = {
  notes: [
    {
      id: 1,
      name: "Shopping list",
      created: "20/09/2022",
      category: CategoryNames.TASK,
      content: "Tomatoes, bread",
      dates: [],
      archived: false,
    },
    {
      id: 2,
      name: "The theory of evolution",
      created: "20/09/2022",
      category: CategoryNames.RANDOM_TOUGHT,
      content: "The evolution of Darwin is...",
      dates: [],
      archived: false,
    },
    {
      id: 3,
      name: "New feature",
      created: "20/09/2022",
      category: CategoryNames.IDEA,
      content: "Implement new feature 18/09/2022 and 21/09/2022",
      dates: ["20/09/2022", "20/09/2022"],
      archived: false,
    },
    {
      id: 4,
      name: "William Gaddis",
      created: "20/09/2022",
      category: CategoryNames.TASK,
      content: "Power doesn't corrupt people; people corrupt power",
      dates: [],
      archived: false,
    },
    {
      id: 5,
      name: "Books",
      created: "20/09/2022",
      category: CategoryNames.RANDOM_TOUGHT,
      content: "The learn startup",
      dates: [],
      archived: false,
    },
    {
      id: 6,
      name: "War never changes",
      created: "24/02/2022",
      category: CategoryNames.RANDOM_TOUGHT,
      content: "War never changes beacause it is never justified",
      dates: [],
      archived: true,
    },
    {
      id: 7,
      name: "Start a new project",
      created: "21/09/2022",
      category: CategoryNames.RANDOM_TOUGHT,
      content: "Start a new project 01/10/2022",
      dates: ["01/10/2022"],
      archived: false,
    },
  ],
  modalClosed: true,
  currentNote: {
    id: 0,
    name: "",
    created: "",
    category: CategoryNames.TASK,
    content: "",
    dates: [],
    archived: false,
  },
};
